### ISSUE TITLE
Basic styling

### ISSUE THREAD

**Issue by pwhipp** [SHeffernan/gploop#7]
Select and apply an appropriate responsive bootstrap 3 template

**Comment by pwhipp** [comment]
There are plenty of [bootstrap 3 templates available online](https://www.google.com.au/search?q=bootstrap+3+themes). Quality is variable though so it is best to get your styling person (er... me to start with...) to review for quality before you make a final decision.

**Comment by SHeffernan** [comment]
I have just purchased the following template:
https://wrapbootstrap.com/theme/artificial-reason-responsive-full-pack-WB0307B17
We'll set it up with blues and greens similar to: http://gpnsw.com.au/

The tabs can have surveys and sign-on pages too.
